"""empty message

Revision ID: 059c58caf680
Revises: 
Create Date: 2021-03-17 20:28:50.664197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059c58caf680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ru_eng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ru', sa.String(length=80), nullable=False),
    sa.Column('eng', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ru_eng')
    # ### end Alembic commands ###
