"""empty message

Revision ID: 3099209d15a7
Revises: d1d1a1af9f2b
Create Date: 2021-05-10 14:13:11.690286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3099209d15a7'
down_revision = 'd1d1a1af9f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.Binary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
