"""empty message

Revision ID: 4c817ae8f95c
Revises: 9b78e419beb4
Create Date: 2021-03-17 21:30:26.546121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c817ae8f95c'
down_revision = '9b78e419beb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_user',
    sa.Column('Word_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Word_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ru_eng.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_user')
    # ### end Alembic commands ###
