"""empty message

Revision ID: 971c6cda3c55
Revises: 4c817ae8f95c
Create Date: 2021-03-18 22:46:35.562394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971c6cda3c55'
down_revision = '4c817ae8f95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('some',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telegramid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('some')
    # ### end Alembic commands ###
