"""empty message

Revision ID: ba04e475db55
Revises: 
Create Date: 2021-05-10 21:51:50.111610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba04e475db55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ru_eng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ru', sa.String(length=80), nullable=False),
    sa.Column('eng', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('context', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telegramid', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.LargeBinary(length=1048576), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('word_user',
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('wid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wid'], ['ru_eng.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_user')
    op.drop_table('user')
    op.drop_table('ru_eng')
    # ### end Alembic commands ###
